Controllers/EmailConfigurationController.cs
using ADOAnalyser.DBContext;
using ADOAnalyser.Models;
using ADOAnalyser.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace ADOAnalyser.Controllers
{
    public class EmailConfigurationController : Controller
    {

        private readonly AppDbContext _dbContext;

        public EmailConfigurationController(AppDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public IActionResult Index()
        {
            var emailConfig = _dbContext.EmailConfig.ToList();
            return View(emailConfig);
        }

        [HttpPost]
        public  IActionResult SaveEmail(EmailConfig model)
        {
            TempData["AlertEmail"] = null;
            var existing = _dbContext.EmailConfig.Where(a => a.EmailId.ToUpper().Equals(model.EmailId.ToUpper())).Count();
            if (existing > 0)
            {
                TempData["AlertEmail"] = "Email already exist.";
            }
            else
            {
                var runResult = new EmailConfig
                {
                    EmailId = model.EmailId,
                    ModifiedDate = DateTime.Now,
                    CreatedDate = DateTime.Now,
                    IsActive = true,
                };
                _dbContext.EmailConfig.Add(runResult);
                _dbContext.SaveChanges();
            }
            return RedirectToAction("Index"); 
        }

        public IActionResult InActive(int id, bool status)
        {
            TempData["AlertEmail"] = null;
            var emailData = _dbContext.EmailConfig.FirstOrDefault(a => a.Id == id);

            if (emailData != null)
            {
                emailData.IsActive = status ? false : true;
                emailData.ModifiedDate = DateTime.Now;
                _dbContext.EmailConfig.Update(emailData);
                _dbContext.SaveChanges();
                TempData["AlertEmail"] = "Email Updated successfully.";
            }
            else
            {
                TempData["AlertEmail"] = "Unable to retrieve the data.";
            }
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            TempData["AlertEmail"] = null;
            var emailData = _dbContext.EmailConfig.FirstOrDefault(a => a.Id == id);

            if (emailData != null)
            {
                _dbContext.EmailConfig.Remove(emailData);
                _dbContext.SaveChanges();

                TempData["AlertEmail"] = "Email Deleted successfully.";
            }
            else
            {
                TempData["AlertEmail"] = "Email not found.";
            }
            return RedirectToAction("Index");
        }
    }
}

Views/EmailConfiguration/Index.cshtml
@model List<ADOAnalyser.Models.EmailConfig>
@{
    ViewData["Title"] = "Notification";
}
@if (TempData["AlertEmail"] != null)
{
    <script>
        alert('@Html.Raw(TempData["AlertEmail"])');
        TempData["AlertMessage"] = null;
    </script>
}
<section id="emailConfigurations" class="content">
    <div class="header" style="font-weight:bold">Email Configuration</div>
    <div class="row  mb-3">
        <form asp-controller="EmailConfiguration" asp-action="SaveEmail" method="post">
            <label class="col-md-12 form-label">
                Email:<br />
                <input type="email" name="EmailId" required class="form-control" placeholder="firstname.lastname@civica.com" style="width: 100%; padding: 8px; margin-top: 5px; margin-bottom: 15px;" />
            </label>
            <button id="saveEmailBtn"  class="col-md-2 btn btn-primary">Save</button>
        </form>
    </div>

    <div class="row">
        <div class="col-md-12 table-responsive">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Email ID</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    @if (Model != null && Model.Any())
                    {
                        foreach (var project in Model)
                        {
                            string active = @project.IsActive ? "Active" : "InActive";
                            string action = @project.IsActive ? "InActive" : "Active";
                            <tr>
                                <td>@project.Id</td>
                                <td>@project.EmailId</td>
                                <td>@active</td>
                                <td>
                                    <a asp-controller="EmailConfiguration" asp-action="InActive" asp-route-id="@project.Id" style="margin-right:5px;min-width:80px; text-align:center;" asp-route-status="@project.IsActive" class="@(project.IsActive ? "btn btn-danger btn-sm" : "btn btn-success btn-sm")">
                                        @action
                                    </a>
                                    <a asp-controller="EmailConfiguration" asp-action="Delete" asp-route-id="@project.Id" style="min-width:80px; text-align:center;"  class="btn btn-primary btn-sm" onclick="return confirm('Are you sure you want to delete this email?');">
                                        Delete
                                    </a>
                                </td>
                            </tr>
                        }
                    }
                    else
                    {
                        <tr>
                            <td colspan="9" class="text-center">No work items found for this sprint.</td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>

    </div>
</section>